config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :images, only: [:index, :new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get 'oauth/connect', to: 'oauth#connect'
  get 'oauth/callback', to: 'oauth#callback'
  get "oauth/tweet" => "oauth/tweet"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :image_file
  validates :title, presence: true, length: {maximum: 30}
  validates :image_file, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  #relation
  has_many :images

  #validation
  validates :user_id, uniqueness: true, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  before_action :authorize_login

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @image = current_user.images.build
  end

  def index
    @images = current_user.images.order(id: :desc)
  end

  def create
    @image = current_user.images.build(image_params)
    if @image.save
      redirect_to images_path
    else
      @errors = []
      @errors.concat(@image.errors.full_messages.each{|msg|msg})
      render 'new'
    end
  end

  private

  def image_params
    params.require(:image).permit(:title, :image_file)
  end


end

app/controllers/oauth_controller.rb
require 'net/http'

class OauthController < ApplicationController

  def connect
    uri = URI(oauth_uri[:authorization_uri])
    params = {client_id: oauth_params[:client_id],
              response_type: oauth_params[:response_type],
              redirect_uri: oauth_params[:redirect_uri],
              scope: oauth_params[:scope],
              state: oauth_params[:state]}
    uri.query = params.to_query
    redirect_to uri.to_s
  end

  def callback
    if params[:code]
      uri = URI(oauth_uri[:access_token_uri])
      res = Net::HTTP.post_form(uri, {
        code: params[:code],
        client_id: oauth_params[:client_id],
        client_secret: oauth_params[:client_secret],
        redirect_uri: oauth_params[:redirect_uri],
        grant_type: oauth_params[:grant_type]
      })
      if res.is_a?(Net::HTTPSuccess)
        data = JSON.parse(res.body)
        session[:access_token] = data['access_token']
        redirect_to images_path
      else
        flash[:error] = 'Failed to get access token'
        redirect_to images_path
      end
    else
      flash[:error] = 'Missing authorization code'
      redirect_to images_path
    end
  end

  def tweet
    image = current_user.images.find(params[:id])
    uri = URI(oauth_uri[:tweet_uri])
    body = {
      text: image.title,
      url: url_for(image.image_file)
    }.to_json

    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Post.new(uri)
    request.content_type = 'application/json'
    request['Authorization'] = "Bearer #{session[:access_token]}"
    request.body = body

    response = http.request(request)

    redirect_to images_path if response.code.to_i == 201
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize_login

  def new
    redirect_to images_path if logged_in?
  end

  def create
    @user = User.find_by(user_id: params[:session][:user_id])
    if @user&.authenticate(params[:session][:password])
      session[:user_id] = @user.user_id
      redirect_to images_path
    else
      @errors = []
      @errors.concat(["ユーザーIDを入力してください"]) if params[:session][:user_id].blank?
      @errors.concat(["パスワードを入力してください"]) if params[:session][:password].blank?
      @errors.concat(['ユーザーIDとパスワードが一致するユーザーが存在しない']) if params[:session][:user_id].present? && params[:session][:password].present?
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    session.delete(:access_token)
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(user_id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def authorize_login
    redirect_to root_path unless logged_in?
  end

  def oauth_uri
    {
      authorization_uri: ENV['UNIFA_OAUTH_URI'] || 'http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/authorize',
      access_token_uri: ENV['UNIFA_RESPONSE_URI'] || 'http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/token',
      tweet_uri: ENV['UNIFA_TWEET_URI'] || 'http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/api/tweets',
    }
  end

  def oauth_params
    {
      client_id: ENV['UNIFA_OAUTH_CLIENT_ID'] || 'g6-zCw8r8VzF9DRwuxCBPZKjhqmfbzk0Jhn6Ez3Kaas',
      client_secret: ENV['UNIFA_OAUTH_CLIENT_SECRET'] || 'QhZ7PAexuVv1SmaHxT3AqVI5IMMj_Skbl1uJv89oUus',
      redirect_uri: ENV['UNIFA_REDIRECT_URI'] || 'http://localhost:3000/oauth/callback',
      response_type: 'code',
      grant_type: 'authorization_code',
      scope: 'write_tweet',
      state: nil
    }
  end
end

app/views/images/index.html.haml
= render partial: "share/logout"
= link_to '写真アップロード', new_image_path, class: 'btn btn-primary'
- if session[:access_token].present?
  = link_to 'MyTweetAppと連携中', oauth_connect_path, class: 'btn btn-primary disabled'
- else
  = link_to 'MyTweetAppと連携', oauth_connect_path, class: 'btn btn-primary'

%h1 写真⼀覧
.image-list
  - @images.each do |image|
    .image-item
      .image-title= image.title
      = image_tag image.image_file, class: 'img-thumbnail'
      - if session[:access_token].present?
        = link_to 'ツイートする', oauth_tweet_path({id: image.id}), class: 'btn btn-primary'

app/views/images/new.html.haml
= render partial: "share/logout"
%h1 写真アップロード
= form_for @image, html: { multipart: true } do |f|
  = render partial: "share/error_messages"
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :image_file
    = f.file_field :image_file, class: 'form-control'
  = f.submit "アップロード", class: 'btn btn-primary'
  = link_to 'キャンセル', images_path, class: 'btn btn-secondary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Photo-Management-App
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"

  %body
  = yield

app/views/share/_error_messages.html.haml
- if @errors.present?
  %ul
  - @errors.each do |error|
    %li.alert.alert-danger= error

app/views/share/_logout.html.haml
= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-secondary'